### ISSUE TITLE
Disparity results in incorrect point cloud

### ISSUE THREAD

**Issue by darren-harton** [labforge/sdk-demos#30]
I've noticed that when I get disparity values back from the Bottlenose camera, running `cv2.reprojectImageTo3D` results in a point cloud that is about 40% too large. Otherwise, the points look correct.

To test, I tried calculating the disparity on my own by requesting raw images from the camera. In this case the resulting point cloud is scaled correctly.

In addition, I've tried comparing rectified images coming off of the camera to images that I've rectified myself. What I found is that the images are basically identical except that they are shifted relative to each other. The offset is about 10 x -3 pixels.

Firmware:
DeviceModelName: BN_4K_4GB_320MB_CS_ST
DeviceVersion: 0.4
DeviceFirmwareVersion: v0.2.132

calibration.yaml
```yaml
cam0:
 fx: 1322.477467104818
 fy: 1323.751092313471
 cx: 949.786919379760
 cy: 555.350700278323

 k1: -0.266834378242
 k2: 0.155438140035
 p1: -0.000309996016
 p2: 0.000047213813
 k3: -0.054694611579

 tvec: [0.000000000000, 0.000000000000, 0.000000000000]
 rvec: [0.000000000000, 0.000000000000, 0.000000000000]

 width: 1920
 height: 1080

cam1:
 fx: 1320.753362065004
 fy: 1321.894620230395
 cx: 969.575226893761
 cy: 520.765496143764

 k1: -0.269198805094
 k2: 0.164478644729
 p1: 0.000136121511
 p2: 0.000105676147
 k3: -0.063760466874

 tvec: [-0.133988077477, -0.000193804114, -0.000745757388]
 rvec: [-0.000855856506, 0.001549896790, -0.001169957099]

 width: 1920
 height: 1080
```

[sample_imgs.zip](https://github.com/labforge/sdk-demos/files/14512136/sample_imgs.zip)
